"""Local operator console for the integrated flagship demonstration.

The browser never receives a platform token.  This service is deliberately a local
demo proxy that reads the synthetic identities generated by ``bootstrap-local`` and
forwards narrowly defined actions to existing control APIs.  Production deployments
must replace it with an authenticated UI and a backend-for-frontend identity exchange.
"""

from __future__ import annotations

import asyncio
import json
import os
from pathlib import Path
from uuid import uuid4

import httpx
from fastapi import FastAPI, HTTPException
from fastapi.responses import FileResponse
from pydantic import BaseModel, Field

STATIC = Path(__file__).resolve().parents[1] / "operator_console" / "static"
TOKENS_PATH = Path(os.getenv("CONSOLE_TOKENS_PATH", "/run/identity/tokens.json"))

app = FastAPI(title="Flagship Operator Console", version="0.1.0")


class ConsoleIntegrationRequest(BaseModel):
    """A deliberately small form forwarded to the existing self-service contract."""

    service_name: str = Field(pattern=r"^[a-z][a-z0-9-]{2,62}$")
    model: str = Field(min_length=1, max_length=120)
    owner: str = Field(pattern=r"^[a-z][a-z0-9-]{2,62}$")
    environment: str = Field(default="development", pattern=r"^(development|staging)$")


# These are Compose service names, not browser-provided URLs. The toggle controls
# only an explicitly simulated local network state for a known fixture device.
EDGE_AGENT_URLS = {
    "edge-search-001": "http://edge-device-search:8080",
    "edge-constrained-001": "http://edge-device-constrained:8080",
}


def _tokens() -> dict[str, str]:
    try:
        return json.loads(TOKENS_PATH.read_text())
    except (OSError, json.JSONDecodeError) as error:
        raise HTTPException(503, "local operator identities are unavailable") from error


def _url(name: str, default: str) -> str:
    return os.getenv(name, default).rstrip("/")


async def _request(
    client: httpx.AsyncClient,
    method: str,
    url: str,
    *,
    token_key: str | None = None,
    json_body: dict | None = None,
    headers: dict[str, str] | None = None,
) -> dict:
    request_headers = dict(headers or {})
    if token_key:
        request_headers["Authorization"] = f"Bearer {_tokens()[token_key]}"
    try:
        response = await client.request(method, url, json=json_body, headers=request_headers)
        response.raise_for_status()
        return response.json()
    except (httpx.HTTPError, ValueError) as error:
        return {"_error": str(error)}


async def _snapshot() -> dict:
    gateway = _url("GATEWAY_URL", "http://gateway-1:8080")
    release = _url("RELEASE_CONTROL_URL", "http://release-control:8080")
    remediation = _url("REMEDIATION_CONTROL_URL", "http://remediation-control:8080")
    edge = _url("EDGE_CONTROL_URL", "http://edge-control:8080")
    self_service = _url("SELF_SERVICE_URL", "http://developer-self-service:8080")
    agent_tools = _url("AGENT_TOOLS_URL", "http://agent-tools:8080")
    sandbox = _url("SANDBOX_CONTROL_URL", "http://sandbox-control:8080")
    prometheus = _url("PROMETHEUS_URL", "http://prometheus:9090")
    mlflow = _url("MLFLOW_URL", "http://mlflow:5000")

    async with httpx.AsyncClient(timeout=4.0) as client:
        calls = await asyncio.gather(
            _request(client, "GET", f"{gateway}/platform/v1/tenants", token_key="admin"),
            _request(client, "GET", f"{gateway}/platform/v1/models", token_key="admin"),
            _request(client, "GET", f"{gateway}/platform/v1/deployments", token_key="admin"),
            _request(client, "GET", f"{gateway}/platform/v1/capacity", token_key="admin"),
            _request(client, "GET", f"{release}/release/v1/plans", token_key="admin"),
            _request(client, "GET", f"{remediation}/remediation/v1/incidents", token_key="admin"),
            _request(client, "GET", f"{edge}/edge/v1/devices"),
            _request(client, "GET", f"{self_service}/developer/v1/inference-integrations", token_key="search"),
            _request(client, "GET", f"{agent_tools}/agent/v1/tools", token_key="delegated_agent"),
            _request(client, "GET", f"{agent_tools}/agent/v1/audit", token_key="delegated_agent"),
            _request(client, "GET", f"{sandbox}/sandbox/v1/tasks", token_key="sandbox_agent"),
            _request(client, "GET", f"{prometheus}/api/v1/query?query=sum(inference_gateway_requests_total)"),
            _request(client, "GET", f"{prometheus}/api/v1/query?query=sum(inference_gateway_throttles_total)"),
            _request(client, "GET", f"{mlflow}/api/2.0/mlflow/registered-models/search?max_results=20"),
        )
    keys = (
        "tenants", "models", "deployments", "capacity", "release_plans", "incidents",
        "devices", "integrations", "agent_tools", "agent_audit", "sandbox_tasks", "requests", "throttles", "registry",
    )
    return dict(zip(keys, calls, strict=True))


def _items(payload: dict, key: str) -> list[dict]:
    value = payload.get(key, [])
    return value if isinstance(value, list) else []


async def _gateway_snapshot(client: httpx.AsyncClient) -> tuple[str, list[dict], list[dict], list[dict]]:
    gateway = _url("GATEWAY_URL", "http://gateway-1:8080")
    tenants, models, deployments = await asyncio.gather(
        _request(client, "GET", f"{gateway}/platform/v1/tenants", token_key="admin"),
        _request(client, "GET", f"{gateway}/platform/v1/models", token_key="admin"),
        _request(client, "GET", f"{gateway}/platform/v1/deployments", token_key="admin"),
    )
    return (
        gateway,
        tenants if isinstance(tenants, list) else [],
        models if isinstance(models, list) else [],
        deployments if isinstance(deployments, list) else [],
    )


async def _prometheus_query(client: httpx.AsyncClient, query: str) -> dict:
    """Run one fixed server-side PromQL query for the local console.

    This intentionally does not expose a browser-controlled PromQL proxy. Model
    aliases are validated by the gateway rollout lookup before reaching this helper.
    """

    prometheus = _url("PROMETHEUS_URL", "http://prometheus:9090")
    try:
        response = await client.get(f"{prometheus}/api/v1/query", params={"query": query})
        response.raise_for_status()
        body = response.json()
        if body.get("status") != "success":
            return {"_error": "Prometheus did not return a successful query"}
        return body.get("data", {})
    except (httpx.HTTPError, ValueError) as error:
        return {"_error": str(error)}


async def _model_telemetry(client: httpx.AsyncClient, alias: str) -> dict[str, dict]:
    # JSON quoting produces a PromQL-safe string literal and prevents the alias from
    # altering the fixed query shape.
    model = json.dumps(alias)
    queries = {
        "requests": f"sum(inference_gateway_requests_total{{model={model}}})",
        "outcomes": f"sum by (outcome) (inference_gateway_requests_total{{model={model}}})",
        "p95_latency_seconds": (
            "histogram_quantile(0.95, sum(rate("
            f"inference_gateway_request_duration_seconds_bucket{{model={model}}}[5m]"
            ")) by (le))"
        ),
        "p95_ttft_seconds": (
            "histogram_quantile(0.95, sum(rate("
            f"inference_gateway_ttft_seconds_bucket{{model={model}}}[5m]"
            ")) by (le))"
        ),
        "tokens": f"sum(inference_gateway_tokens_total{{model={model}}})",
        "estimated_cost_usd": f"sum(inference_gateway_estimated_cost_usd_total{{model={model}}})",
        "slo": f"sum by (status) (inference_gateway_request_slo_evaluations_total{{model={model}}})",
        "release_phase": f"sum by (phase) (inference_gateway_release_correlated_requests_total{{model={model}}})",
    }
    results = await asyncio.gather(*(_prometheus_query(client, query) for query in queries.values()))
    return dict(zip(queries, results, strict=True))


@app.get("/healthz")
def healthz() -> dict[str, str]:
    _tokens()
    return {"status": "ok", "mode": "local-demo-bff"}


@app.get("/")
def index() -> FileResponse:
    return FileResponse(STATIC / "index.html")


@app.get("/assets/{asset}")
def assets(asset: str) -> FileResponse:
    safe = Path(asset).name
    if safe != asset or safe not in {"app.js", "styles.css"}:
        raise HTTPException(404, "asset not found")
    return FileResponse(STATIC / safe)


@app.get("/console/v1/overview")
async def overview() -> dict:
    return await _snapshot()


@app.get("/console/v1/tenants/{tenant_id}")
async def tenant_detail(tenant_id: str) -> dict:
    async with httpx.AsyncClient(timeout=4.0) as client:
        gateway, tenants, models, deployments = await _gateway_snapshot(client)
        tenant = next((item for item in tenants if item.get("id") == tenant_id), None)
        if tenant is None:
            raise HTTPException(404, "tenant not found")
        usage = await _request(client, "GET", f"{gateway}/platform/v1/usage/{tenant_id}", token_key="admin")
    return {
        "tenant": tenant,
        "usage": usage,
        "models": models,
        "deployments": deployments,
    }


@app.get("/console/v1/models/{alias}")
async def model_detail(alias: str) -> dict:
    gateway = _url("GATEWAY_URL", "http://gateway-1:8080")
    mlflow = _url("MLFLOW_URL", "http://mlflow:5000")
    async with httpx.AsyncClient(timeout=4.0) as client:
        rollout, deployments, registry = await asyncio.gather(
            _request(client, "GET", f"{gateway}/platform/v1/rollouts/{alias}", token_key="admin"),
            _request(client, "GET", f"{gateway}/platform/v1/deployments", token_key="admin"),
            _request(client, "GET", f"{mlflow}/api/2.0/mlflow/registered-models/search?max_results=20"),
        )
        if "_error" in rollout:
            raise HTTPException(404, "model alias not found")
        telemetry = await _model_telemetry(client, alias)
    if "_error" in rollout:
        raise HTTPException(404, "model alias not found")
    return {
        "rollout": rollout,
        "deployments": deployments,
        "registry": registry,
        "telemetry": telemetry,
        "grafana_url": f"{_url('GRAFANA_URL', 'http://localhost:3002')}/d/afzqe0e3u9logf/inference-gateway?var-model={alias}",
    }


@app.get("/console/v1/releases/{plan_id}")
async def release_detail(plan_id: str) -> dict:
    release = _url("RELEASE_CONTROL_URL", "http://release-control:8080")
    async with httpx.AsyncClient(timeout=4.0) as client:
        result = await _request(client, "GET", f"{release}/release/v1/plans/{plan_id}", token_key="admin")
    if "_error" in result:
        raise HTTPException(404, "release plan not found")
    return result


@app.get("/console/v1/incidents/{incident_id}")
async def incident_detail(incident_id: str) -> dict:
    remediation = _url("REMEDIATION_CONTROL_URL", "http://remediation-control:8080")
    async with httpx.AsyncClient(timeout=4.0) as client:
        incident, timeline = await asyncio.gather(
            _request(client, "GET", f"{remediation}/remediation/v1/incidents/{incident_id}", token_key="admin"),
            _request(client, "GET", f"{remediation}/remediation/v1/incidents/{incident_id}/timeline", token_key="admin"),
        )
    if "_error" in incident:
        raise HTTPException(404, "incident not found")
    event_rows = timeline if isinstance(timeline, list) else []
    plan_ids = {
        event.get("details", {}).get("plan_id")
        for event in event_rows
        if isinstance(event, dict) and isinstance(event.get("details"), dict)
    }
    async with httpx.AsyncClient(timeout=4.0) as client:
        plans = await asyncio.gather(*(
            _request(client, "GET", f"{remediation}/remediation/v1/plans/{plan_id}", token_key="admin")
            for plan_id in sorted(plan_id for plan_id in plan_ids if isinstance(plan_id, str))
        ))
    return {
        "incident": incident.get("incident", incident),
        "timeline": event_rows,
        "plans": [plan for plan in plans if "_error" not in plan],
    }


@app.get("/console/v1/remediation/plans/{plan_id}")
async def remediation_plan_detail(plan_id: str) -> dict:
    remediation = _url("REMEDIATION_CONTROL_URL", "http://remediation-control:8080")
    async with httpx.AsyncClient(timeout=4.0) as client:
        result = await _request(
            client,
            "GET",
            f"{remediation}/remediation/v1/plans/{plan_id}",
            token_key="admin",
        )
    if "_error" in result:
        raise HTTPException(404, "remediation plan not found")
    return result


@app.get("/console/v1/agents")
async def agent_detail() -> dict:
    agent_tools = _url("AGENT_TOOLS_URL", "http://agent-tools:8080")
    async with httpx.AsyncClient(timeout=4.0) as client:
        tools, audit = await asyncio.gather(
            _request(client, "GET", f"{agent_tools}/agent/v1/tools", token_key="delegated_agent"),
            _request(client, "GET", f"{agent_tools}/agent/v1/audit", token_key="delegated_agent"),
        )
    return {"tools": tools, "audit": audit}


@app.get("/console/v1/sandbox/tasks/{task_id}")
async def sandbox_task_detail(task_id: str) -> dict:
    sandbox = _url("SANDBOX_CONTROL_URL", "http://sandbox-control:8080")
    async with httpx.AsyncClient(timeout=4.0) as client:
        tasks = await _request(client, "GET", f"{sandbox}/sandbox/v1/tasks", token_key="sandbox_agent")
    task = next((item for item in _items(tasks, "tasks") if item.get("id") == task_id), None)
    if task is None:
        raise HTTPException(404, "sandbox task not found")
    return {"task": task}


@app.get("/console/v1/developer/integrations/{profile_id}")
async def developer_profile_detail(profile_id: str) -> dict:
    self_service = _url("SELF_SERVICE_URL", "http://developer-self-service:8080")
    async with httpx.AsyncClient(timeout=4.0) as client:
        result = await _request(
            client,
            "GET",
            f"{self_service}/developer/v1/inference-integrations/{profile_id}",
            token_key="search",
        )
    if "_error" in result:
        raise HTTPException(404, "developer integration profile not found")
    return result


@app.get("/console/v1/edge/devices/{device_id}")
async def edge_device_detail(device_id: str) -> dict:
    edge = _url("EDGE_CONTROL_URL", "http://edge-control:8080")
    async with httpx.AsyncClient(timeout=4.0) as client:
        devices = await _request(client, "GET", f"{edge}/edge/v1/devices")
    device = next((item for item in _items(devices, "devices") if item.get("device_id") == device_id), None)
    if device is None:
        raise HTTPException(404, "edge device not found")
    return {"device": device, "hardware": devices.get("hardware", "SIMULATED")}


async def _release_action(plan_id: str | None, action: str, canary_weight: int = 10) -> dict:
    release = _url("RELEASE_CONTROL_URL", "http://release-control:8080")
    method, path, token_key, body = "POST", "", "admin", None
    if action == "create":
        path = f"/release/v1/plans?canary_weight={canary_weight}"
    elif action == "approve" and plan_id:
        path, token_key = f"/release/v1/plans/{plan_id}/approve", "approver"
    elif action in {"canary", "promote", "rollback"} and plan_id:
        path = f"/release/v1/plans/{plan_id}/{action}"
    else:
        raise HTTPException(422, "unknown release action")
    async with httpx.AsyncClient(timeout=6.0) as client:
        result = await _request(client, method, f"{release}{path}", token_key=token_key, json_body=body)
    if "_error" in result:
        raise HTTPException(409, result["_error"])
    return result


@app.post("/console/v1/releases/{action}")
async def release_action(action: str, plan_id: str | None = None, canary_weight: int = 10) -> dict:
    if not 1 <= canary_weight <= 99:
        raise HTTPException(422, "canary_weight must be between 1 and 99")
    return await _release_action(plan_id, action, canary_weight)


@app.post("/console/v1/sandbox/{task_kind}")
async def sandbox_task(task_kind: str) -> dict:
    if task_kind not in {"fixture_patch", "containment_probe"}:
        raise HTTPException(422, "only named fixture tasks are permitted")
    sandbox = _url("SANDBOX_CONTROL_URL", "http://sandbox-control:8080")
    async with httpx.AsyncClient(timeout=20.0) as client:
        result = await _request(
            client,
            "POST",
            f"{sandbox}/sandbox/v1/tasks",
            token_key="sandbox_agent",
            json_body={"task_kind": task_kind},
            headers={"Idempotency-Key": f"console-{task_kind}-{uuid4()}"},
        )
    if "_error" in result:
        raise HTTPException(502, result["_error"])
    return result


@app.post("/console/v1/developer/integrations", status_code=201)
async def create_developer_integration(request: ConsoleIntegrationRequest) -> dict:
    """Create a tenant-bound profile through the existing developer service.

    The browser supplies only the constrained integration fields. The BFF supplies
    the local developer identity and a fresh idempotency key; the downstream service
    remains authoritative for tenant/model authorization and persistence.
    """

    self_service = _url("SELF_SERVICE_URL", "http://developer-self-service:8080")
    async with httpx.AsyncClient(timeout=6.0) as client:
        result = await _request(
            client,
            "POST",
            f"{self_service}/developer/v1/inference-integrations",
            token_key="search",
            json_body=request.model_dump(),
            headers={"Idempotency-Key": f"console-profile-{uuid4()}"},
        )
    if "_error" in result:
        raise HTTPException(409, result["_error"])
    return result


@app.post("/console/v1/remediation/incidents/{incident_id}/plan")
async def create_remediation_plan(incident_id: str) -> dict:
    remediation = _url("REMEDIATION_CONTROL_URL", "http://remediation-control:8080")
    async with httpx.AsyncClient(timeout=6.0) as client:
        result = await _request(
            client,
            "POST",
            f"{remediation}/remediation/v1/incidents/{incident_id}/plans",
            token_key="admin",
        )
    if "_error" in result:
        raise HTTPException(409, result["_error"])
    return result


@app.post("/console/v1/remediation/plans/{plan_id}/{action}")
async def remediation_plan_action(plan_id: str, action: str) -> dict:
    if action not in {"approve", "execute"}:
        raise HTTPException(422, "unknown remediation action")
    remediation = _url("REMEDIATION_CONTROL_URL", "http://remediation-control:8080")
    # Release approval and remediation approval are deliberately separate local
    # identities. Reusing the release approver would fail the remediation policy and
    # blur the independently auditable approval boundary.
    token_key = "remediation_approver" if action == "approve" else "admin"
    async with httpx.AsyncClient(timeout=10.0) as client:
        result = await _request(
            client,
            "POST",
            f"{remediation}/remediation/v1/plans/{plan_id}/{action}",
            token_key=token_key,
        )
    if "_error" in result:
        raise HTTPException(409, result["_error"])
    return result


@app.post("/console/v1/edge/devices/{device_id}/network/{state}")
async def set_simulated_edge_network(device_id: str, state: str) -> dict:
    if state not in {"online", "offline"}:
        raise HTTPException(422, "simulated network state must be online or offline")
    endpoint = EDGE_AGENT_URLS.get(device_id)
    if endpoint is None:
        raise HTTPException(404, "fixture edge device not found")
    async with httpx.AsyncClient(timeout=5.0) as client:
        result = await _request(client, "POST", f"{endpoint}/edge/v1/network/{state}")
    if "_error" in result:
        raise HTTPException(502, result["_error"])
    return result
