"""Local operator console for the integrated flagship demonstration.

The browser never receives a platform token.  This service is deliberately a local
demo proxy that reads the synthetic identities generated by ``bootstrap-local`` and
forwards narrowly defined actions to existing control APIs.  Production deployments
must replace it with an authenticated UI and a backend-for-frontend identity exchange.
"""

from __future__ import annotations

import asyncio
import json
import os
from pathlib import Path
from uuid import uuid4

import httpx
from fastapi import FastAPI, HTTPException
from fastapi.responses import FileResponse

STATIC = Path(__file__).resolve().parents[1] / "operator_console" / "static"
TOKENS_PATH = Path(os.getenv("CONSOLE_TOKENS_PATH", "/run/identity/tokens.json"))

app = FastAPI(title="Flagship Operator Console", version="0.1.0")


def _tokens() -> dict[str, str]:
    try:
        return json.loads(TOKENS_PATH.read_text())
    except (OSError, json.JSONDecodeError) as error:
        raise HTTPException(503, "local operator identities are unavailable") from error


def _url(name: str, default: str) -> str:
    return os.getenv(name, default).rstrip("/")


async def _request(
    client: httpx.AsyncClient,
    method: str,
    url: str,
    *,
    token_key: str | None = None,
    json_body: dict | None = None,
    headers: dict[str, str] | None = None,
) -> dict:
    request_headers = dict(headers or {})
    if token_key:
        request_headers["Authorization"] = f"Bearer {_tokens()[token_key]}"
    try:
        response = await client.request(method, url, json=json_body, headers=request_headers)
        response.raise_for_status()
        return response.json()
    except (httpx.HTTPError, ValueError) as error:
        return {"_error": str(error)}


async def _snapshot() -> dict:
    gateway = _url("GATEWAY_URL", "http://gateway-1:8080")
    release = _url("RELEASE_CONTROL_URL", "http://release-control:8080")
    remediation = _url("REMEDIATION_CONTROL_URL", "http://remediation-control:8080")
    edge = _url("EDGE_CONTROL_URL", "http://edge-control:8080")
    self_service = _url("SELF_SERVICE_URL", "http://developer-self-service:8080")
    agent_tools = _url("AGENT_TOOLS_URL", "http://agent-tools:8080")
    sandbox = _url("SANDBOX_CONTROL_URL", "http://sandbox-control:8080")
    prometheus = _url("PROMETHEUS_URL", "http://prometheus:9090")
    mlflow = _url("MLFLOW_URL", "http://mlflow:5000")

    async with httpx.AsyncClient(timeout=4.0) as client:
        calls = await asyncio.gather(
            _request(client, "GET", f"{gateway}/platform/v1/tenants", token_key="admin"),
            _request(client, "GET", f"{gateway}/platform/v1/models", token_key="admin"),
            _request(client, "GET", f"{gateway}/platform/v1/deployments", token_key="admin"),
            _request(client, "GET", f"{gateway}/platform/v1/capacity", token_key="admin"),
            _request(client, "GET", f"{release}/release/v1/plans", token_key="admin"),
            _request(client, "GET", f"{remediation}/remediation/v1/incidents", token_key="admin"),
            _request(client, "GET", f"{edge}/edge/v1/devices"),
            _request(client, "GET", f"{self_service}/developer/v1/inference-integrations", token_key="search"),
            _request(client, "GET", f"{agent_tools}/agent/v1/audit", token_key="delegated_agent"),
            _request(client, "GET", f"{sandbox}/sandbox/v1/tasks", token_key="sandbox_agent"),
            _request(client, "GET", f"{prometheus}/api/v1/query?query=sum(inference_gateway_requests_total)"),
            _request(client, "GET", f"{prometheus}/api/v1/query?query=sum(inference_gateway_throttles_total)"),
            _request(client, "GET", f"{mlflow}/api/2.0/mlflow/registered-models/search?max_results=20"),
        )
    keys = (
        "tenants", "models", "deployments", "capacity", "release_plans", "incidents",
        "devices", "integrations", "agent_audit", "sandbox_tasks", "requests", "throttles", "registry",
    )
    return dict(zip(keys, calls, strict=True))


@app.get("/healthz")
def healthz() -> dict[str, str]:
    _tokens()
    return {"status": "ok", "mode": "local-demo-bff"}


@app.get("/")
def index() -> FileResponse:
    return FileResponse(STATIC / "index.html")


@app.get("/assets/{asset}")
def assets(asset: str) -> FileResponse:
    safe = Path(asset).name
    if safe != asset or safe not in {"app.js", "styles.css"}:
        raise HTTPException(404, "asset not found")
    return FileResponse(STATIC / safe)


@app.get("/console/v1/overview")
async def overview() -> dict:
    return await _snapshot()


async def _release_action(plan_id: str | None, action: str, canary_weight: int = 10) -> dict:
    release = _url("RELEASE_CONTROL_URL", "http://release-control:8080")
    method, path, token_key, body = "POST", "", "admin", None
    if action == "create":
        path = f"/release/v1/plans?canary_weight={canary_weight}"
    elif action == "approve" and plan_id:
        path, token_key = f"/release/v1/plans/{plan_id}/approve", "approver"
    elif action in {"canary", "promote", "rollback"} and plan_id:
        path = f"/release/v1/plans/{plan_id}/{action}"
    else:
        raise HTTPException(422, "unknown release action")
    async with httpx.AsyncClient(timeout=6.0) as client:
        result = await _request(client, method, f"{release}{path}", token_key=token_key, json_body=body)
    if "_error" in result:
        raise HTTPException(409, result["_error"])
    return result


@app.post("/console/v1/releases/{action}")
async def release_action(action: str, plan_id: str | None = None, canary_weight: int = 10) -> dict:
    if not 1 <= canary_weight <= 99:
        raise HTTPException(422, "canary_weight must be between 1 and 99")
    return await _release_action(plan_id, action, canary_weight)


@app.post("/console/v1/sandbox/{task_kind}")
async def sandbox_task(task_kind: str) -> dict:
    if task_kind not in {"fixture_patch", "containment_probe"}:
        raise HTTPException(422, "only named fixture tasks are permitted")
    sandbox = _url("SANDBOX_CONTROL_URL", "http://sandbox-control:8080")
    async with httpx.AsyncClient(timeout=20.0) as client:
        result = await _request(
            client,
            "POST",
            f"{sandbox}/sandbox/v1/tasks",
            token_key="sandbox_agent",
            json_body={"task_kind": task_kind},
            headers={"Idempotency-Key": f"console-{task_kind}-{uuid4()}"},
        )
    if "_error" in result:
        raise HTTPException(502, result["_error"])
    return result
